wandb_version: 1

batch_size:
  desc: null
  value: 64
depth:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.1
model:
  desc: null
  value: MLP
optimizer:
  desc: null
  value: Adam
width:
  desc: null
  value: 1024
bias:
  desc: null
  value: true
ETF_fc:
  desc: null
  value: false
fixdim:
  desc: null
  value: 0
SOTA:
  desc: null
  value: false
gpu_id:
  desc: null
  value: 0
seed:
  desc: null
  value: 6
use_cudnn:
  desc: null
  value: true
dataset:
  desc: null
  value: cifar10
data_dir:
  desc: null
  value: ~/data
uid:
  desc: null
  value: tmp
force:
  desc: null
  value: true
epochs:
  desc: null
  value: 1
loss:
  desc: null
  value: CrossEntropy
sample_size:
  desc: null
  value: null
lr:
  desc: null
  value: 0.001
history_size:
  desc: null
  value: 10
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706590125.360666
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
