wandb_version: 1

model:
  desc: null
  value: "ResNet(\n  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3,\
    \ 3), bias=False)\n  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n  (relu): ReLU(inplace=True)\n  (maxpool): MaxPool2d(kernel_size=3,\
    \ stride=2, padding=1, dilation=1, ceil_mode=False)\n  (layer1): Sequential(\n\
    \    (0): BasicBlock(\n      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1,\
    \ 1), padding=(1, 1), bias=False)\n      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1,\
    \ affine=True, track_running_stats=True)\n      (relu): ReLU(inplace=True)\n \
    \     (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1),\
    \ bias=False)\n      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n    )\n    (1): BasicBlock(\n      (conv1): Conv2d(64,\
    \ 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn1):\
    \ BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(64, 64, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(64,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n    )\n  )\n\
    \  (layer2): Sequential(\n    (0): BasicBlock(\n      (conv1): Conv2d(64, 128,\
    \ kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n      (bn1):\
    \ BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(128, 128, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(128,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n      (downsample):\
    \ Sequential(\n        (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2),\
    \ bias=False)\n        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n      )\n    )\n    (1): BasicBlock(\n      (conv1):\
    \ Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n\
    \      (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(128, 128, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(128,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n    )\n  )\n\
    \  (layer3): Sequential(\n    (0): BasicBlock(\n      (conv1): Conv2d(128, 256,\
    \ kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n      (bn1):\
    \ BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(256, 256, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(256,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n      (downsample):\
    \ Sequential(\n        (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2),\
    \ bias=False)\n        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n      )\n    )\n    (1): BasicBlock(\n      (conv1):\
    \ Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n\
    \      (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(256, 256, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(256,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n    )\n  )\n\
    \  (layer4): Sequential(\n    (0): BasicBlock(\n      (conv1): Conv2d(256, 512,\
    \ kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)\n      (bn1):\
    \ BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(512, 512, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(512,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n      (downsample):\
    \ Sequential(\n        (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2),\
    \ bias=False)\n        (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n      )\n    )\n    (1): BasicBlock(\n      (conv1):\
    \ Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)\n\
    \      (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n\
    \      (relu): ReLU(inplace=True)\n      (conv2): Conv2d(512, 10, kernel_size=(3,\
    \ 3), stride=(1, 1), padding=(1, 1), bias=False)\n      (bn2): BatchNorm2d(10,\
    \ eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)\n      (downsample):\
    \ Sequential(\n        (0): Conv2d(512, 10, kernel_size=(1, 1), stride=(1, 1),\
    \ bias=False)\n        (1): BatchNorm2d(10, eps=1e-05, momentum=0.1, affine=True,\
    \ track_running_stats=True)\n      )\n    )\n  )\n  (avgpool): AdaptiveAvgPool2d(output_size=(1,\
    \ 1))\n  (fc): Linear(in_features=10, out_features=10, bias=True)\n)"
bias:
  desc: null
  value: true
ETF_fc:
  desc: null
  value: true
fixdim:
  desc: null
  value: 1
SOTA:
  desc: null
  value: false
width:
  desc: null
  value: 32
depth:
  desc: null
  value: 6
gpu_id:
  desc: null
  value: 0
seed:
  desc: null
  value: 6
use_cudnn:
  desc: null
  value: true
dataset:
  desc: null
  value: cifar10
data_dir:
  desc: null
  value: ~/data
uid:
  desc: null
  value: Resnet18-design-Adam
force:
  desc: null
  value: true
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 64
loss:
  desc: null
  value: CrossEntropy
sample_size:
  desc: null
  value: null
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
device:
  desc: null
  value: mps
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708339504.6129
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
