wandb_version: 1

batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.1
loss:
  desc: null
  value: CrossEntropy
model:
  desc: null
  value: ResNet18_adapt
optimizer:
  desc: null
  value: SGD
width:
  desc: null
  value: 1024
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706592954.881257
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
