wandb_version: 1

method:
  desc: null
  value: grid
metric:
  desc: null
  value:
    name: loss
    goal: minimize
parameters:
  desc: null
  value:
    model:
      values:
      - MLP
      - ResNet18_adapt
    learning_rate:
      values:
      - 0.1
      - 0.05
      - 0.001
    optimizer:
      values:
      - Adam
      - SGD
      - LBFGS
    width:
      values:
      - 1024
      - 2048
      - 4096
    depth:
      values:
      - 4
      - 8
      - 12
    batch_size:
      values:
      - 64
      - 256
      - 2048
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706589390.602735
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
