wandb_version: 1

batch_size:
  value: 64
depth:
  value: 4
epochs:
  value: 10
learning_rate:
  value: 0.1
loss:
  value: CrossEntropy
model:
  value: MLP
optimizer:
  value: Adam
width:
  value: 2048
