wandb_version: 1

model:
  desc: null
  value: resnet50
bias:
  desc: null
  value: true
ETF_fc:
  desc: null
  value: false
fixdim:
  desc: null
  value: 0
SOTA:
  desc: null
  value: true
width:
  desc: null
  value: 32
depth:
  desc: null
  value: 6
gpu_id:
  desc: null
  value: 0
seed:
  desc: null
  value: 6
use_cudnn:
  desc: null
  value: true
dataset:
  desc: null
  value: cifar10
data_dir:
  desc: null
  value: ~/data
uid:
  desc: null
  value: tmp
force:
  desc: null
  value: true
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 32
loss:
  desc: null
  value: CrossEntropy
sample_size:
  desc: null
  value: null
lr:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: Adam
history_size:
  desc: null
  value: 10
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1707211704.181637
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 15
      - 16
      - 23
      4: 3.11.5
      5: 0.16.1
      6: 4.32.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
